
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Preset {
    Default = 0,
    ModernMetal = 1,
    Djent = 2,
    Thall = 3,
    Hardcore = 4,
    Deathcore = 5,
    ProgMetal = 6,
    Bass = 7,
    Clean = 8,
}

impl Preset {
    pub fn from_index(index: f32) -> Self {
        match index as i32 {
            1 => Preset::ModernMetal,
            2 => Preset::Djent,
            3 => Preset::Thall,
            4 => Preset::Hardcore,
            5 => Preset::Deathcore,
            6 => Preset::ProgMetal,
            7 => Preset::Bass,
            8 => Preset::Clean,
            _ => Preset::Default,
        }
    }

    pub fn name(&self) -> &'static str {
        match self {
            Preset::Default => "Default",
            Preset::ModernMetal => "Modern Metal",
            Preset::Djent => "Djent",
            Preset::Thall => "Thall",
            Preset::Hardcore => "Hardcore",
            Preset::Deathcore => "Deathcore",
            Preset::ProgMetal => "Prog Metal",
            Preset::Bass => "Bass",
            Preset::Clean => "Clean",
        }
    }

    pub fn get_values(&self) -> PresetValues {
        match self {
            Preset::Default => PresetValues::default(),
            Preset::ModernMetal => PresetValues {
                threshold_db: -35.0,
                attack_ms: 0.5,
                hold_ms: 15.0,
                release_ms: 100.0,
                range_db: -80.0,
                sidechain_hpf_hz: 150.0,
                sidechain_lpf_hz: 8000.0,
                lookahead_ms: 2.0,
                adaptive_release: true,
                pick_detector_enabled: true,
                pick_sensitivity: 0.6,
                palm_mute_enabled: true,
                palm_mute_threshold: 0.4,
                smart_gate_enabled: false,
                adaptive_threshold_enabled: false,
                adaptive_threshold_speed: 0.1,
                noise_classification_enabled: false,
            },
            Preset::Djent => PresetValues {
                threshold_db: -40.0,
                attack_ms: 0.1,
                hold_ms: 5.0,
                release_ms: 50.0,
                range_db: -80.0,
                sidechain_hpf_hz: 200.0,
                sidechain_lpf_hz: 6000.0,
                lookahead_ms: 5.0,
                adaptive_release: true,
                pick_detector_enabled: true,
                pick_sensitivity: 0.8,
                palm_mute_enabled: true,
                palm_mute_threshold: 0.5,
                smart_gate_enabled: true,
                adaptive_threshold_enabled: true,
                adaptive_threshold_speed: 0.2,
                noise_classification_enabled: false,
            },
            Preset::Thall => PresetValues {
                threshold_db: -30.0,
                attack_ms: 5.0,
                hold_ms: 50.0,
                release_ms: 200.0,
                range_db: -60.0,
                sidechain_hpf_hz: 100.0,
                sidechain_lpf_hz: 12000.0,
                lookahead_ms: 0.0,
                adaptive_release: true,
                pick_detector_enabled: false,
                pick_sensitivity: 0.5,
                palm_mute_enabled: false,
                palm_mute_threshold: 0.3,
                smart_gate_enabled: false,
                adaptive_threshold_enabled: true,
                adaptive_threshold_speed: 0.05,
                noise_classification_enabled: true,
            },
            Preset::Hardcore => PresetValues {
                threshold_db: -45.0,
                attack_ms: 0.05,
                hold_ms: 10.0,
                release_ms: 80.0,
                range_db: -80.0,
                sidechain_hpf_hz: 250.0,
                sidechain_lpf_hz: 5000.0,
                lookahead_ms: 3.0,
                adaptive_release: false,
                pick_detector_enabled: true,
                pick_sensitivity: 0.9,
                palm_mute_enabled: true,
                palm_mute_threshold: 0.6,
                smart_gate_enabled: false,
                adaptive_threshold_enabled: false,
                adaptive_threshold_speed: 0.1,
                noise_classification_enabled: false,
            },
            Preset::Deathcore => PresetValues {
                threshold_db: -50.0,
                attack_ms: 0.02,
                hold_ms: 5.0,
                release_ms: 60.0,
                range_db: -80.0,
                sidechain_hpf_hz: 300.0,
                sidechain_lpf_hz: 4000.0,
                lookahead_ms: 4.0,
                adaptive_release: false,
                pick_detector_enabled: true,
                pick_sensitivity: 0.95,
                palm_mute_enabled: true,
                palm_mute_threshold: 0.7,
                smart_gate_enabled: true,
                adaptive_threshold_enabled: true,
                adaptive_threshold_speed: 0.3,
                noise_classification_enabled: false,
            },
            Preset::ProgMetal => PresetValues {
                threshold_db: -38.0,
                attack_ms: 1.0,
                hold_ms: 20.0,
                release_ms: 150.0,
                range_db: -70.0,
                sidechain_hpf_hz: 120.0,
                sidechain_lpf_hz: 10000.0,
                lookahead_ms: 1.0,
                adaptive_release: true,
                pick_detector_enabled: true,
                pick_sensitivity: 0.5,
                palm_mute_enabled: true,
                palm_mute_threshold: 0.35,
                smart_gate_enabled: false,
                adaptive_threshold_enabled: true,
                adaptive_threshold_speed: 0.1,
                noise_classification_enabled: true,
            },
            Preset::Bass => PresetValues {
                threshold_db: -25.0,
                attack_ms: 2.0,
                hold_ms: 30.0,
                release_ms: 200.0,
                range_db: -50.0,
                sidechain_hpf_hz: 50.0,
                sidechain_lpf_hz: 5000.0,
                lookahead_ms: 0.0,
                adaptive_release: true,
                pick_detector_enabled: false,
                pick_sensitivity: 0.5,
                palm_mute_enabled: false,
                palm_mute_threshold: 0.3,
                smart_gate_enabled: false,
                adaptive_threshold_enabled: true,
                adaptive_threshold_speed: 0.05,
                noise_classification_enabled: false,
            },
            Preset::Clean => PresetValues {
                threshold_db: -50.0,
                attack_ms: 10.0,
                hold_ms: 100.0,
                release_ms: 500.0,
                range_db: -40.0,
                sidechain_hpf_hz: 80.0,
                sidechain_lpf_hz: 15000.0,
                lookahead_ms: 0.0,
                adaptive_release: true,
                pick_detector_enabled: false,
                pick_sensitivity: 0.5,
                palm_mute_enabled: false,
                palm_mute_threshold: 0.3,
                smart_gate_enabled: false,
                adaptive_threshold_enabled: false,
                adaptive_threshold_speed: 0.1,
                noise_classification_enabled: false,
            },
        }
    }
}

#[derive(Debug, Clone, Copy, serde::Serialize, serde::Deserialize)]
pub struct PresetValues {
    pub threshold_db: f32,
    pub attack_ms: f32,
    pub hold_ms: f32,
    pub release_ms: f32,
    pub range_db: f32,
    pub sidechain_hpf_hz: f32,
    pub sidechain_lpf_hz: f32,
    pub lookahead_ms: f32,
    pub adaptive_release: bool,
    pub pick_detector_enabled: bool,
    pub pick_sensitivity: f32,
    pub palm_mute_enabled: bool,
    pub palm_mute_threshold: f32,
    pub smart_gate_enabled: bool,
    pub adaptive_threshold_enabled: bool,
    pub adaptive_threshold_speed: f32,
    pub noise_classification_enabled: bool,
}

impl Default for PresetValues {
    fn default() -> Self {
        Self {
            threshold_db: -30.0,
            attack_ms: 0.5,
            hold_ms: 10.0,
            release_ms: 80.0,
            range_db: -80.0,
            sidechain_hpf_hz: 220.0,
            sidechain_lpf_hz: 20000.0,
            lookahead_ms: 0.0,
            adaptive_release: false,
            pick_detector_enabled: false,
            pick_sensitivity: 0.5,
            palm_mute_enabled: false,
            palm_mute_threshold: 0.3,
            smart_gate_enabled: false,
            adaptive_threshold_enabled: false,
            adaptive_threshold_speed: 0.1,
            noise_classification_enabled: false,
        }
    }
}
